[package]
name = "merc_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "merc_demo"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
numpy = "0.29"
pyo3-arrow = "0.19"
arrow-array = "59"
arrow-schema = "59"
rayon = "1"
arrow-buffer = "59"

[profile.release]
opt-level = 3
